server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: gateway-secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/demo
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/demo

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: orders
          uri: http://localhost:9001
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: products
          uri: http://localhost:9002
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
